# HEADER_TYPE: LEGACY_REWRITE_CANDIDATE
# EXECUTION: FORBIDDEN
# IMPORT: FORBIDDEN
# AUTHORITY: NONE
# DESTINATION: Logos_System_Rebuild
# ARCHIVE_AFTER_REWRITE: REQUIRED

"""
Persist the formal identity generated by the recursion engine to canonical locations
so the consciousness subsystems and the logos core can read it.

Writes a small JSON file to each target path.
"""
import json
from pathlib import Path
import sys

ROOT = Path.cwd()
DISCHARGE = ROOT / "Logos_Agent" / "state" / "lem_discharge_state.json"
if not DISCHARGE.exists():
    print("No discharge state found at", DISCHARGE)
    sys.exit(1)

with open(DISCHARGE, "r", encoding="utf-8") as fh:
    data = json.load(fh)

# Try to derive the canonical formal identity. The bridge/engine writes a formatted
# token as `formal_identity` in some reports, but the discharge record may only have
# agent_id/resolved_at. We'll create a deterministic identity if not present.
formal_identity = data.get("formal_identity") or data.get("generated_identity")
if not formal_identity:
    # fallback deterministic composition
    import hashlib
    raw = f"{data.get('agent_id','')}-{data.get('resolved_at','')}-{data.get('proof_file','')}"
    formal_identity = "LOGOS_AGENT_IDENTITY::" + data.get("agent_id","UNKNOWN") + "::" + hashlib.sha256(raw.encode()).hexdigest()

payload = {
    "formal_identity": formal_identity,
    "agent_id": data.get("agent_id"),
    "resolved_at": data.get("resolved_at"),
    "proof_file": data.get("proof_file"),
}

# Target files (user requested):
targets = [
    ROOT / "Synthetic_Cognition_Protocol" / "consciousness" / "agent_identity.json",
    ROOT / "Advanced_Reasoning_Protocol" / "logos_core copy" / "agent_identity.json",
    ROOT / "Logos_Agent" / "state" / "agent_identity.json",
]

for t in targets:
    try:
        t.parent.mkdir(parents=True, exist_ok=True)
        with open(t, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
        print("Wrote identity to", t)
    except Exception as exc:
        print("Failed to write to", t, exc)

print("Completed. Formal identity:")
print(formal_identity)
