#!/bin/bash
# LOGOS Interface Quick Reference

echo "🤖 LOGOS Protocol-Grounded Interface"
echo "====================================="
echo ""
echo "📍 TWO MODES:"
echo ""
echo "1️⃣  CHAT MODE (scripts/logos_chat.py)"
echo "   • LLM synthesizes answers"
echo "   • Natural conversation"
echo "   • ⚠️  May hallucinate"
echo "   Usage: ./logos"
echo ""
echo "2️⃣  PROTOCOL MODE (scripts/logos_interface.py) ← RECOMMENDED"
echo "   • LLM only routes requests"
echo "   • Returns raw LOGOS output"
echo "   • ✅ Zero hallucination"
echo "   Usage: python3 scripts/logos_interface.py"
echo ""
echo "📝 FIRST TIME SETUP:"
echo "   python3 scripts/scan_repo.py        # Build knowledge base"
echo "   python3 scripts/logos_interface.py  # Start protocol interface"
echo ""
echo "💡 EXAMPLE QUESTIONS:"
echo "   • Are the proofs verified?"
echo "   • What are the 8 axioms?"
echo "   • Show me the mission status"
echo "   • List files in scripts/"
echo ""
echo "🔒 SAFETY GUARANTEE:"
echo "   Protocol mode returns ONLY actual LOGOS execution output."
echo "   The LLM cannot make up answers or hallucinate."
echo ""
echo "📖 Full docs: docs/PROTOCOL_GROUNDED_INTERFACE.md"
echo ""
